djangotweet/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("tweetapp.urls")),
    path("",include("django.contrib.auth.urls")),
]

tweetapp/urls.py
from django.urls import path
from . import views

app_name = 'tweetapp'

urlpatterns = [
    path("",views.listtweet,name="listtweet"),
    path("addtweet/",views.addtweet,name="addtweet"),
    path('addtweetbyform',views.addtweetbyform,name='addtweetbyform'),
    path('addtweetbymodelform',views.addtweetbymodelform,name='addtweetbymodelform'),
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('deletetweet/<int:id>',views.deletetweet,name='deletetweet')
]

tweetapp/models.py
from django.db import models
from django.core.validators  import MinLengthValidator,MaxLengthValidator
from django.contrib.auth.models import User
# Create your models here.

class Tweet(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    message = models.CharField(max_length=150,validators=[MinLengthValidator(1),MaxLengthValidator(150)])

    def __str__(self):
        return f"user: {self.username} message: {self.message}"

tweetapp/forms.py
from django import forms
from django.forms import ModelForm
from tweetapp.models import Tweet
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class AddTweetForm(forms.Form):
    nickname_input = forms.CharField(label="Nickname",max_length=50)
    message_input = forms.CharField(label="Message",max_length=150,widget=forms.Textarea(attrs={"class":"tweetmessage"}))


class AddTweetModelForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ['username', 'message']  # fields = '__all__' for all fields

tweetapp/views.py
from django.shortcuts import render,redirect
from . import models
from django.urls import reverse, reverse_lazy
from tweetapp.forms import AddTweetForm,AddTweetModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
# Create your views here.

def listtweet(request):
    all_tweets = models.Tweet.objects.all()
    tweet_dict = {"tweets": all_tweets}
    return render(request,'tweetapp/listtweet.html',context=tweet_dict)

@login_required(login_url="/login")
def addtweet(request):
    if request.POST:
        message = request.POST["message"]
        models.Tweet.objects.create(username=request.user,message=message)
        return redirect(reverse("tweetapp:listtweet"))
    else:
        return render(request,'tweetapp/addtweet.html')
    

def addtweetbyform(request):
    if request.method == "POST":
        form = AddTweetForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname_input"]
            message = form.cleaned_data["message_input"]
            models.Tweet.objects.create(nickname=nickname,message=message)
            return redirect(reverse("tweetapp:listtweet"))
        else:
            print("eroorrrr")
            return render(request,'tweetapp/addtweetbyform.html',context={'form':form})
    else:
        form = AddTweetForm()
        return render(request,'tweetapp/addtweetbyform.html',context={'form':form})
    

def addtweetbymodelform(request):
    if request.method == "POST":
        form = AddTweetModelForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname"]
            message = form.cleaned_data["message"]
            models.Tweet.objects.create(nickname=nickname,message=message)
            return redirect(reverse("tweetapp:listtweet"))
        else:
            print("eroorrrr")
            return render(request,'tweetapp/addtweetbymodelform.html',context={'form':form})
    else:
        form = AddTweetModelForm()
        return render(request,'tweetapp/addtweetbymodelform.html',context={'form':form})
    
    ## app ismi : url name yani şu isimdeki appte ki şu url nameine sahip urlye git reversede gçörürüz
    ## reverse() fonksiyonu url name ile url pathini döndürür
    ## renderda app içindeki templates klasörü / app ismiyle oluştrmş klasör altındaki html sayfalarını göstrer context veriler
    ## request.method == "POST" : formu post ile gönderiyorsa

@login_required
def deletetweet(request,id):
    tweet = models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect('tweetapp:listtweet')

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"

templates/base.html
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tweet App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'tweetapp/css/customform.css'%}">
    <link rel="stylesheet" href="{% static 'tweetapp/css/listtweet.css' %}">
</head>
<body>
       
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container-fluid">
      <a class="navbar-brand">Tweet App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'tweetapp:listtweet'%}">Tweet List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tweetapp:addtweet'%}">Add Tweet</a>
                </li>
                <!-- <li class="nav-item"></li>
                    <a class="nav-link" href="{% url 'tweetapp:addtweetbyform'%}">Add Tweet By Form</a>
                </li>
                <li class="nav-item"></li>
                <a class="nav-link" href="{% url 'tweetapp:addtweetbymodelform'%}">Add Tweet By Model Form</a>
                </li>
                 -->
                <li class="nav-item"></li>
                <a class="nav-link" href="{% url 'login'%}">Login</a>
               </li>   

               <!-- <li class="nav-item"></li>
                <a class="nav-link" href="{% url 'logout' %}?next=/">Logout</a>
               </li>   -->
               <li class="nav-item">      
                    <form action="{% url 'logout' %}?next=/" method="post">       
                              {% csrf_token %}
                            <button type="submit" class="nav-link btn btn-link">Logout</button>     
                    </form>   
                </li>

                <li class="nav-item"></li>
                <a class="nav-link" href="{% url 'tweetapp:signup'%}">Signup</a>
               </li> 
               
            </ul>
        
      </div>
    </div>
  </nav>
    {%block content%}

    {%endblock%}

</body>
</html>

<!-- "{% url 'login'%}" bu da urls.py de bu isimli url pathindeki viewi uygula eğer app in 
                             içinde bi url path ise başına appismi: url path namesini koy böylelikle basıldığında o path url sayfasına gitsin
                             örnek 127.0.0.8000/addtweet -> addtweet tweetapp in içinde yazarken tweetapp:addtweet yazdık tıkladığımızda
                             bizi götürdüğü id üstte çünkü tweetapp pathinde url kısmı = " " boş ama bu "{% url 'tweetapp:addtweet'%}" 
                             tweetappdeki namesi addtweet olan pathten bizi götürüyo 
                        -->

tweetapp/templates/tweetapp/addtweet.html
{%extends "base.html" %}

{%block content%}
<h1>Add tweet Page</h1>
<form action="" method="post">
    {%csrf_token%}
    <!-- <div class="mb-3">
      <label for="nickname" class="form-label">Nickname</label>
      <input type="text" class="form-control" id="nickname" name="nickname">
      
    </div> -->
    <div class="mb-3">
      <label for="message" class="form-label">Message</label>
      <input type="text" class="form-control" id="message" name="message">
    </div>
    <button type="submit" class="btn btn-primary">Send Tweet</button>
  </form>
{%endblock%}

tweetapp/templates/tweetapp/addtweetbyform.html
{%extends "base.html" %}
{%load static%}

{%block content%}

<div class="container">
    <div class="tweetform">
        <h1>Add tweet By Form Page</h1>
        <form action="" method="post">
            {%csrf_token%}
            {{form}} 
            <button type="submit" id="buttto" class="btn btn-danger">Send Tweet</button>
        </form>
    </div>
</div>

{%endblock%}

tweetapp/templates/tweetapp/addtweetbymodelform.html
{%extends "base.html" %}
{%load static%}

{%block content%}

<div class="container">
    <div class="tweetform">
        <h1>Add tweet By Model Form Page</h1>
        <form action="" method="post">
            {%csrf_token%}
            {{form}} 
            <button type="submit" class="btn btn-primary">Send Model Tweet</button>
        </form>
    </div>
</div>

{%endblock%}

tweetapp/templates/tweetapp/listtweet.html
{%extends "base.html" %}
{% load static %}

{%block content%}

<div class="first">
    
    <div class="container" >
        
        <ul>
            {% for tweet in tweets %}
                <div class="card" style="width: 36rem;">
                    
                    <div class="card-body">
                        <h5 class="card-title">{{tweet.username}}</h5>
                        <p class="card-text">{{tweet.message}}</p>
                    
                    </div>
                    {%if tweet.username == user %}
                        <a href="{% url 'tweetapp:deletetweet' id=tweet.id %}" class="btn btn-danger">Delete</a>
                    {%endif%}
                </div>
            {% endfor %}
        </ul>
    </div>
</div>
{%endblock%}